### ISSUE TITLE
Checked modules seem to be executed

### ISSUE THREAD

**Issue by dessant** [autocomplete-python/autocomplete-python#161]
After upgrading from 1.2.4 to 1.4.3, i'm getting errors like these.

![capture](https://cloud.githubusercontent.com/assets/7513068/12344046/da1bb7d2-bb41-11e5-95d0-9fd9ee11d629.PNG)

Those logs must originate from executing the modules which are parsed by the plugin.

**Comment by sadovnychyi** [comment]
I did change the behaviour of error output to hide only Jedi related errors by simple "jedi" substring lookup. Likely the problem been here even before 1.4.3.

Any steps to reproduce this?

**Comment by dessant** [comment]
I've seen it with kivy so far, in one module i do `import kivy`, and in a second one i type `from kivy.core.window import Window`. The errors appear most of the time, but not always.

**Comment by sadovnychyi** [comment]
What I can do is only to hide such errors just like before.
Don't have time to mess around trying to reproduce it right now.

**Comment by Fiveside** [comment]
I'm getting similar behavior.  One of the imports inside autocomplete-python is failing because its attempting to import a file within my project.

```
Traceback (most recent call last):
  File "/home/erich/.atom/packages/autocomplete-python/lib/completion.py", line 6, in <module>
    import traceback
  File "/home/erich/.pyenv/versions/3.5.0/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/home/erich/.pyenv/versions/3.5.0/lib/python3.5/linecache.py", line 8, in <module>
    import functools
  File "/home/erich/.pyenv/versions/3.5.0/lib/python3.5/functools.py", line 22, in <module>
    from types import MappingProxyType
  File "/home/erich/workspace/trex/ethos/types.py", line 4, in <module>
    from dateutil.parser import parse as parse_datetime
  File "/home/erich/.pyenv/versions/trex/lib/python3.5/site-packages/dateutil/parser.py", line 25, in <module>
    from six import text_type, binary_type, integer_types
  File "/home/erich/.pyenv/versions/trex/lib/python3.5/site-packages/six.py", line 124, in <module>
    class _LazyModule(types.ModuleType):
AttributeError: module 'types' has no attribute 'ModuleType'
```

Autocomplete-python is attempting to import `traceback`.  The python standard library then attempts to import `types` which is somehow mapped to the `types.py` file inside my project.  This error spawns every time the completion attempts to run, but can be temporarily be rectified by closing all files from that folder and running a single completion from a different folder so that the imports are resolved properly.  

The rest of the traceback looks strange because I'm using [pyenv](https://github.com/yyuu/pyenv) to manage my virutalenv environment

**Comment by sadovnychyi** [comment]
@Fiveside I guess the same thing will happen if you will try to import traceback from your project, isn't? Maybe, I could somehow force autocomplete-python to make imports *only* from stdlib, so you will not be able to ovverride them.

Need to take a look onto it.

**Comment by Fiveside** [comment]
@sadovnychyi Actually importing `traceback` from the project works fine because of the way the project is structured and the simplified import rules introduced in (I believe) python 2.6

```
root/
↳entrypoint.py
↳ethos/
 ↳types.py
 ↳other modules and packages
```

The `entrypoint.py` file is where imports are resolved from.  importing `ethos` gives access to all of the modules for this package, and any imports from files inside the project must be either relative imports or absolute imports relative to the entrypoint (or standard library packages and installed packages).

Thus, importing `traceback` from any file in the same folder as `types.py` doesn't accidentally replace the system types package.

**Comment by kopias** [comment]
this still happens with kivy with python 2 on ubuntu 15.10 and windows 7
to reproduce just install kivy using officiall instructions on kivy.org and try something like:

"from kivy.uix.scrollview import" (the error notification popup appears)

the autocomplete still works as expected and the error is displayed onece per session.

For a workaround: is there a easy way to disable this package all notifications?

**Comment by kopias** [comment]
found that chenging in kivy config.ini file ( https://kivy.org/docs/guide/config.html )
"log_level" from "info" to "warning" is a fix/workaround for this problem

in my opinion this is not an real issue and should be closed

btw. thx for this addon

**Comment by sadovnychyi** [comment]
Thanks for getting back to this. I was able to reproduce this and I think I got a fix.

See https://github.com/davidhalter/jedi/issues/793.

Feel free to re-open this if it's isn't fixed for you in 1.8.9.
